const popupImage = document.querySelector('.popup_type_image');
const popupAdd = document.querySelector('.popup_type_add-card');
const popupEdit = document.querySelector('.popup_type_edit-profile');
export const popupImagePic = popupImage.querySelector('.popup__image');
export const popupSubtitle = popupImage.querySelector('.popup__subtitle');
export const addButton = document.querySelector('.profile__add-button')
export const editButton = document.querySelector('.profile__edit-button');
export const photoGrid = document.querySelector('.photo-grid');
export const addSubmitButton = popupAdd.querySelector('.popup__add-button');
export const editSubmitButton = popupEdit.querySelector('.popup__add-button');
export const cardName = popupAdd.querySelector('.popup__input_type_place');
export const cardImage = popupAdd.querySelector('.popup__input_type_image');
export const nameInput = popupEdit.querySelector('.popup__input_type_name');
export const jobInput = popupEdit.querySelector('.popup__input_type_description');
export const profileName = document.querySelector('.profile__name');
export const profileJob = document.querySelector('.profile__description');
export const avatar = document.querySelector('.profile__avatar');
export const avatarEditButton = document.querySelector('.profile__avatar-edit-icon')
